test_that("valid_team_names works", {
  valid_fbs <-
c("Air Force"             ,"Akron"                 ,"Alabama"
 ,"Appalachian State"     ,"Arizona"               ,"Arizona State"
 ,"Arkansas"              ,"Arkansas State"        ,"Army"
 ,"Auburn"                ,"Ball State"            ,"Baylor"
 ,"Boise State"           ,"Boston College"        ,"Bowling Green"
 ,"Buffalo"               ,"BYU"                   ,"California"
 ,"Central Michigan"      ,"Charlotte"             ,"Cincinnati"
 ,"Clemson"               ,"Coastal Carolina"      ,"Colorado"
 ,"Colorado State"        ,"Connecticut"           ,"Duke"
 ,"East Carolina"         ,"Eastern Michigan"      ,"Florida"
 ,"Florida Atlantic"      ,"Florida International" ,"Florida State"
 ,"Fresno State"          ,"Georgia"               ,"Georgia Southern"
 ,"Georgia State"         ,"Georgia Tech"          ,"Hawai'i"
 ,"Houston"               ,"Illinois"              ,"Indiana"
 ,"Iowa"                  ,"Iowa State"            ,"Kansas"
 ,"Kansas State"          ,"Kent State"            ,"Kentucky"
 ,"Liberty"               ,"Louisiana"             ,"Louisiana Monroe"
 ,"Louisiana Tech"        ,"Louisville"            ,"LSU"
 ,"Marshall"              ,"Maryland"              ,"Memphis"
 ,"Miami"                 ,"Miami (OH)"            ,"Michigan"
 ,"Michigan State"        ,"Middle Tennessee"      ,"Minnesota"
 ,"Mississippi State"     ,"Missouri"              ,"Navy"
 ,"NC State"              ,"Nebraska"              ,"Nevada"
 ,"New Mexico"            ,"New Mexico State"      ,"North Carolina"
 ,"Northern Illinois"     ,"North Texas"           ,"Northwestern"
 ,"Notre Dame"            ,"Ohio"                  ,"Ohio State"
 ,"Oklahoma"              ,"Oklahoma State"        ,"Old Dominion"
 ,"Ole Miss"              ,"Oregon"                ,"Oregon State"
 ,"Penn State"            ,"Pittsburgh"            ,"Purdue"
 ,"Rice"                  ,"Rutgers"               ,"San Diego State"
 ,"San José State"        ,"SMU"                   ,"South Alabama"
 ,"South Carolina"        ,"Southern Mississippi"  ,"South Florida"
 ,"Stanford"              ,"Syracuse"              ,"TCU"
 ,"Temple"                ,"Tennessee"             ,"Texas"
 ,"Texas A&M"             ,"Texas State"           ,"Texas Tech"
 ,"Toledo"                ,"Troy"                  ,"Tulane"
 ,"Tulsa"                 ,"UAB"                   ,"UCF"
 ,"UCLA"                  ,"UMass"                 ,"UNLV"
 ,"USC"                   ,"Utah"                  ,"Utah State"
 ,"UTEP"                  ,"UT San Antonio"        ,"Vanderbilt"
 ,"Virginia"              ,"Virginia Tech"         ,"Wake Forest"
 ,"Washington"            ,"Washington State"      ,"Western Kentucky"
 ,"Western Michigan"      ,"West Virginia"         ,"Wisconsin"
 ,"Wyoming")

  valid_fcs <-
   c("Abilene Christian"        ,"Alabama A&M"
   ,"Alabama State"            ,"Albany"
   ,"Alcorn State"             ,"Alderson-Broaddus"
   ,"American International"   ,"Amherst College"
   ,"Anderson (IN)"            ,"Arkansas-Pine Bluff"
   ,"Arkansas Tech"            ,"Austin Peay"
   ,"Bemidji State"            ,"Bentley"
   ,"Bethel (TN)"              ,"Bethune-Cookman"
   ,"Bloomsburg"               ,"Bridgewater (VA)"
   ,"Brown"                    ,"Bryant"
   ,"Bucknell"                 ,"Butler"
   ,"California (PA)"          ,"Cal Poly"
   ,"Campbell"                 ,"Carroll (WI)"
   ,"Central Arkansas"         ,"Central Connecticut"
   ,"Central Washington"       ,"Charleston Southern"
   ,"Chattanooga"              ,"Claremont"
   ,"Clarion"                  ,"Colby"
   ,"Colgate"                  ,"Colorado College"
   ,"Columbia"                 ,"Concord"
   ,"Cornell"                  ,"Dakota State"
   ,"Dartmouth"                ,"Davidson"
   ,"Dayton"                   ,"Delaware"
   ,"Delaware State"           ,"Delta State"
   ,"Drake"                    ,"Duquesne"
   ,"Eastern Illinois"         ,"Eastern Kentucky"
   ,"Eastern Washington"       ,"East Stroudsburg"
   ,"East Tennessee State"     ,"Edinboro"
   ,"Elon"                     ,"Ferris State"
   ,"Florida A&M"              ,"Florida Tech"
   ,"Fordham"                  ,"Furman"
   ,"Gannon"                   ,"Gardner-Webb"
   ,"George Mason"             ,"Georgetown"
   ,"Graceland University"     ,"Grambling"
   ,"Grand Valley State"       ,"Hampton"
   ,"Harding"                  ,"Harvard"
   ,"Henderson State"          ,"Holy Cross"
   ,"Houston Baptist"          ,"Howard"
   ,"Idaho"                    ,"Idaho State"
   ,"Illinois State"           ,"Incarnate Word"
   ,"Indiana (PA)"             ,"Indiana State"
   ,"Jackson State"            ,"Jacksonville"
   ,"Jacksonville State"       ,"James Madison"
   ,"Kennesaw State"           ,"Kentucky State"
   ,"Kutztown"                 ,"Lafayette"
   ,"Lamar"                    ,"Lehigh"
   ,"Lenoir-Rhyne"             ,"Lock Haven"
   ,"Maine"                    ,"Marist"
   ,"Mars Hill"                ,"McNeese"
   ,"Mercer"                   ,"Mercyhurst"
   ,"Merrimack"                ,"Michigan Tech"
   ,"Millersville"             ,"Minnesota-Duluth"
   ,"Minnesota State"          ,"Minnesota St-Moorhead"
   ,"Mississippi Valley State" ,"Missouri Baptist"
   ,"Missouri State"           ,"Montana"
   ,"Montana State"            ,"Montana-Western"
   ,"Morehead State"           ,"Morehouse"
   ,"Morgan State"             ,"Murray State"
   ,"Nebraska-Omaha"           ,"New Hampshire"
   ,"New Haven"                ,"New Mexico Highlands"
   ,"Nicholls"                 ,"Norfolk State"
   ,"North Alabama"            ,"North Carolina A&T"
   ,"North Carolina Central"   ,"North Dakota"
   ,"North Dakota State"       ,"Northern Arizona"
   ,"Northern Colorado"        ,"Northern Iowa"
   ,"Northern Michigan"        ,"Northwestern State"
   ,"Northwest Missouri State" ,"Notre Dame College"
   ,"Ouachita Baptist"         ,"Pennsylvania"
   ,"Portland State"           ,"Prairie View"
   ,"Presbyterian College"     ,"Princeton"
   ,"Redlands"                 ,"Rhode Island"
   ,"Richmond"                 ,"Robert Morris"
   ,"Rowan"                    ,"Sacramento State"
   ,"Sacred Heart"             ,"Saginaw Valley"
   ,"Samford"                  ,"Sam Houston State"
   ,"San Diego"
   ,"Savannah State"           ,"Seton Hill College"
   ,"Shenandoah"               ,"Shepherd"
   ,"Shippensburg"             ,"Slippery Rock"
   ,"South Carolina State"     ,"South Dakota"
   ,"South Dakota State"       ,"Southeastern Louisiana"
   ,"Southeast Missouri State" ,"Southern"
   ,"Southern Illinois"        ,"Southern Oregon"
   ,"Southern Utah"            ,"St. Ambrose"
   ,"St. Cloud State"          ,"Stephen F. Austin"
   ,"Stetson"                  ,"St Francis (PA)"
   ,"St. Johns (MN)"           ,"St Lawrence"
   ,"Stony Brook"              ,"St. Peter's"
   ,"St. Thomas (MN)"          ,"Tarleton State"
   ,"Tennessee State"          ,"Tennessee Tech"
   ,"Texas A&M-Commerce"       ,"Texas Southern"
   ,"The Citadel"              ,"Towson"
   ,"Trinity (IL)"             ,"Tuskegee"
   ,"UC Davis"                 ,"UMass Dartmouth"
   ,"UMass Lowell"             ,"UT Martin"
   ,"Valdosta State"           ,"Valparaiso"
   ,"Villanova"                ,"VMI"
   ,"Wagner"                   ,"Washington (MO)"
   ,"Weber State"              ,"West Alabama"
   ,"West Chester"             ,"Western Carolina"
   ,"Western Illinois"         ,"Western Oregon"
   ,"West Texas A&M"           ,"West Virginia Tech"
   ,"Wheaton College (Ill)"    ,"William Jewell College"
   ,"William & Mary"           ,"Winston-Salem"
   ,"Wisconsin-Platteville"    ,"Wofford"
   ,"Worcester State College"  ,"Wright State University"
   ,"Yale"                     ,"Youngstown State"
   ,"Chowan"                   ,"Dixie State"
   ,"Hofstra"                  ,"Northeastern"
   ,"Shorter"                  ,"University of Mary" )

  valid_d3 <-
  c("Adrian"                   ,"Albion"
  ,"Albright"                  ,"Alfred State"
  ,"Alfred"                    ,"Allegheny"
  ,"Alma"                      ,"Alvernia"
  ,"Amherst"                   ,"Anderson"
  ,"Anna Maria"                ,"Augsburg"
  ,"Augustana"                 ,"Aurora"
  ,"Austin"                    ,"Averett"
  ,"Baldwin Wallace"           ,"Bates"
  ,"Beloit"                    ,"Benedictine"
  ,"Berry"                     ,"Bethany"
  ,"Bethel"                    ,"Birmingham-Southern"
  ,"Bluffton"                  ,"Bowdoin"
  ,"Brevard"                   ,"Bridgewater State"
  ,"Bridgewater"               ,"Brockport"
  ,"Buena Vista"               ,"Buffalo State"
  ,"Cal Lutheran"              ,"Capital"
  ,"Carleton"                  ,"Carnegie Mellon"
  ,"Carroll"                   ,"Carthage"
  ,"Case Western Reserve"      ,"Castleton"
  ,"Catholic"                  ,"Central"
  ,"Centre"                    ,"Chapman"
  ,"Chicago"                   ,"Christopher Newport"
  ,"Claremont-Mudd-Scripps"    ,"Cortland"
  ,"Crown"                     ,"Curry"
  ,"Dean"                      ,"Defiance"
  ,"Delaware Valley"           ,"Denison"
  ,"DePauw"                    ,"Dickinson"
  ,"Dubuque"                   ,"East Texas Baptist"
  ,"Elmhurst"                  ,"Emory and Henry"
  ,"Endicott"                  ,"Eureka"
  ,"FDU-Florham"               ,"Ferrum"
  ,"Finlandia"                 ,"Fitchburg State"
  ,"Framingham State"          ,"Franklin and Marshall"
  ,"Franklin"                  ,"Gallaudet"
  ,"Geneva"                    ,"George Fox"
  ,"Gettysburg"                ,"Greensboro"
  ,"Greenville"                ,"Grinnell"
  ,"Grove City"                ,"Guilford"
  ,"Gustavus Adolphus"         ,"Hamilton"
  ,"Hamline"                   ,"Hampden-Sydney"
  ,"Hanover"                   ,"Hardin-Simmons"
  ,"Hartwick"                  ,"Heidelberg"
  ,"Hendrix"                   ,"Hiram"
  ,"Hobart"                    ,"Hope"
  ,"Howard Payne"              ,"Huntingdon"
  ,"Husson"                    ,"Illinois College"
  ,"Illinois Wesleyan"         ,"Iowa Wesleyan"
  ,"Ithaca"                    ,"John Carroll"
  ,"Johns Hopkins"             ,"Juniata"
  ,"Kalamazoo"                 ,"Kean"
  ,"Kenyon"                    ,"Keystone"
  ,"King's"                    ,"Knox"
  ,"La Verne"                  ,"Manchester"
  ,"Marietta"                  ,"Martin Luther"
  ,"Mary Hardin-Baylor"        ,"Maryville (Tenn.)"
  ,"Mass-Dartmouth"            ,"Massachusetts Maritime"
  ,"McDaniel"                  ,"McMurry"
  ,"Merchant Marine"           ,"Methodist"
  ,"Middlebury"                ,"Millikin"
  ,"Millsaps"                  ,"Minnesota-Morris"
  ,"Misericordia"              ,"MIT"
  ,"Monmouth"                  ,"Montclair State"
  ,"Moravian"                  ,"Morrisville State"
  ,"Mount St. Joseph"          ,"Mount Union"
  ,"Muhlenberg"                ,"Muskingum"
  ,"N.C. Wesleyan"             ,"Nebraska Wesleyan"
  ,"Nichols"                   ,"North Central (Ill.)"
  ,"North Park"                ,"Northwestern (Minn.)"
  ,"Norwich"                   ,"Simpson"
  ,"Southern Virginia"         ,"Southwestern"
  ,"Springfield"               ,"St. John Fisher"
  ,"St. John's"                ,"St. Lawrence"
  ,"St. Norbert"               ,"St. Olaf"
  ,"St. Scholastica"           ,"St. Thomas"
  ,"St. Vincent"               ,"Stevenson"
  ,"Sul Ross State"            ,"SUNY-Maritime"
  ,"Susquehanna"               ,"TCNJ"
  ,"Texas Lutheran"            ,"Thiel"
  ,"Trine"                     ,"Trinity (Conn.)"
  ,"Trinity (Texas)"           ,"Tufts"
  ,"Union"                     ,"University of New England"
  ,"Ursinus"                   ,"Utica"
  ,"UW-Eau Claire"             ,"UW-La Crosse"
  ,"UW-Oshkosh"                ,"UW-Platteville"
  ,"UW-River Falls"            ,"UW-Stevens Point"
  ,"UW-Stout"                  ,"UW-Whitewater"
  ,"Wabash"                    ,"Wartburg"
  ,"Washington and Jefferson"  ,"Washington and Lee"
  ,"Washington U."             ,"Waynesburg"
  ,"Wesley"                    ,"Wesleyan"
  ,"Western Connecticut"       ,"Western New England"
  ,"Westfield State"           ,"Westminster (Mo.)"
  ,"Westminster (Pa.)"         ,"Wheaton (Ill.)"
  ,"Whittier"                  ,"Whitworth"
  ,"Widener"                   ,"Wilkes"
  ,"Willamette"                ,"William Paterson"
  ,"Williams"                  ,"Wilmington"
  ,"Wisconsin Lutheran"        ,"Wittenberg"
  ,"Wooster"                   ,"Worcester State"
  ,"WPI")

  valid_conf <-
    c("ACC"                 ,"Big 12"              ,"Big Ten"
    ,"SEC"                 ,"Pac-12"              ,"Conference USA"
    ,"Mid-American"        ,"Mountain West"       ,"FBS Independents"
    ,"Big Sky"             ,"MVFC"                ,"Ivy"
    ,"MEAC"                ,"NEC"                 ,"OVC"
    ,"Patriot"             ,"Pioneer"             ,"Southern Conference"
    ,"Southland"           ,"SWAC"                ,"Sun Belt"
    ,"Big South"           ,"CAA"                 ,"NCAA")

  expect_identical(valid_team_names("FBS"), valid_fbs)
  expect_identical(valid_team_names("FCS"), valid_fcs)
  expect_identical(valid_team_names("DIII"), valid_d3)
  expect_identical(valid_team_names("Conference"), valid_conf)
})
